sources:
  - repo: rom-rb/template-gem
    sync:
      - "!.github/workflows/ci.yml"
      - ".github/**/*.*"
      - "spec/*"
      - "*"
  - repo: action-hero/workflows
    sync:
      - ".github/workflows/*.yml"
