engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Lint/UnusedMethodArgument:
        enabled: false
      Rubocop/Lint/UnusedBlockArgument:
        enabled: false
      Rubocop/Metrics/CyclomaticComplexity:
        enabled: true
        Max: 7
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25

ratings:
  paths:
    - lib/**/*.rb

exclude_paths:
  - spec/**/*
  - Rakefile
