language: ruby
dist: xenial
cache: bundler
services:
  - postgresql
  - mysql
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_sql;' -U postgres
  - mysql -u root -e 'create database rom_sql;'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
  - bundle exec rake
rvm:
  - ruby-head
  - 2.6.5
  - 2.5.7
  - 2.4.9
env:
  global:
    - COVERAGE='true'
  matrix:
    - USE_SEQUEL_MASTER=true
    - USE_SEQUEL_MASTER=false
    - USE_ROM_MASTER=true
    - USE_ROM_MASTER=false
matrix:
  include:
    - rvm: jruby-9.2.7.0
      jdk: openjdk8
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://rom-rb.zulipchat.com/api/v1/external/travis?api_key=S1S2GRkXHlzlaCGyUwm7o4lg50IZrwCH&stream=notifications&topic=ci
    on_success: change
    on_failure: always
    on_start: false
