version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: rom-sql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rom-sql

  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: rom-sql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rom-sql
