jobs:
  tests:
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rom_sql
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rom_sql
          POSTGRES_PASSWORD: password
          POSTGRES_USER: rom-sql
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "2.6"
          - "2.4"
          - "jruby"
        include:
          - ruby: "2.6"
            coverage: "true"
          - ruby: "2.7"
            fail_on_warnings: "true"
            dry_types_from_master: "true"
            rom_core_from_master: "true"
            sequel_from_master: "true"
          - ruby: "jruby"
            mysql_dsn: "jdbc:mysql://127.0.0.1:3307/rom_sql?user=root&password=password&sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION&useSSL=false"
            postgres_dsn: "jdbc:postgresql://127.0.0.1:5432/rom_sql?user=rom-sql&password=password"
    env:
      APT_DEPS: "libpq-dev libmysqlclient-dev libsqlite3-dev"
      POSTGRES_DSN: "${{matrix.postgres_dsn}}"
      MYSQL_PORT: 3307
      MYSQL_DSN: "${{matrix.mysql_dsn}}"
      FAIL_ON_WARNINGS: ${{matrix.fail_on_warnings}}
      DRY_TYPES_FROM_MASTER: ${{matrix.dry_types_from_master}}
      ROM_CORE_FROM_MASTER: ${{matrix.rom_core_from_master}}
      SEQUEL_FROM_MASTER: ${{matrix.sequel_from_master}}
