jobs:
  tests:
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3307:3306
        env:
          MYSQL_USER: rom-sql
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rom-sql
      postgres:
        image: postgres:11
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: rom-sql
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rom-sql
    strategy:
      matrix:
        ruby:
          - "2.7.0"
          - "2.6"
          - "2.4"
          - "jruby"
        include:
          - ruby: "2.6"
            coverage: "true"
          - ruby: "2.7.0"
            fail_on_warnings: "true"
            dry_types_from_master: "true"
            rom_core_from_master: "true"
            sequel_from_master: "true"
    env:
      APT_DEPS: "libpq-dev libmysqlclient-dev libsqlite3-dev"
      FAIL_ON_WARNINGS: ${{matrix.fail_on_warnings}}
      DRY_TYPES_FROM_MASTER: ${{matrix.dry_types_from_master}}
      ROM_CORE_FROM_MASTER: ${{matrix.rom_core_from_master}}
      SEQUEL_FROM_MASTER: ${{matrix.sequel_from_master}}
